- src/Messaging/Events/FailureReason.cs
Add additional enum values to `FailureReasons`: `PluginError`, and `ExternalServiceError`
**Ready*
> Additional FailureReasons

- src/Messaging/API/IMessageBrokerPublisherService.cs
- src/Messaging/API/IMessageBrokerSubscriberService.cs
- src/Messaging/Common/Log.cs
- src/Messaging/Messages/Message.cs
- src/Messaging/RabbitMq/RabbitMqConnectionFactory.cs
- src/Messaging/RabbitMq/RabbitMqMessagePublisherService.cs
- src/Messaging/RabbitMq/RabbitMqMessageSubscriberService.cs
- src/Messaging/Test/JsonMessageTest.cs
- src/Messaging/Test/RabbitMq/RabbitMqMessagePublisherServiceTest.cs
- src/Messaging/Test/RabbitMq/RabbitMqMessageSubscriberServiceTest.cs
- Internals change to the `IRabbitMqConnectionFactory` to manage and maintain a single connection per host, username, password, and virtual host combination.  The factory returns a new channel instead of a connection. This guarantees a single connection is used across multiple channels.
- Both `IMessageBrokerPublisherService` and `IMessageBrokerSubscriberService` shall be registered as transient in the hosted service. E.g.,
```
services.AddTransient<RabbitMqMessageSubscriberService>();
services.AddTransient<IMessageBrokerSubscriberService>(implementationFactory =>
{
var options = implementationFactory.GetService<IOptions<InformaticsGatewayConfiguration>>();
var serviceProvider = implementationFactory.GetService<IServiceProvider>();
var logger = …
```
> Ability to convert Message to JsonMessage<T>

- src/Messaging/Common/Credentials.cs
- src/Messaging/Common/MessageValidationException.cs
- src/Messaging/Common/Storage.cs
- src/Messaging/Events/TaskDispatchEvent.cs
- src/Messaging/Test/TaskDispatchEventTest.cs
Given that Task Manager will be generating temporary credentials for accessing the buckets, `Credentials` can be optional for `TaskDispatchEvent.Inputs` and `TaskDispatchEvent.Outputs`.
**Ready**
> Make Credentials optional for TaskDispatchEvent.Inputs/Outputs

- src/Messaging/Events/TaskDispatchEvent.cs
- src/Messaging/Events/TaskExecutionStatus.cs
- src/Messaging/Events/TaskUpdateEvent.cs
Fixes # .
Change task status enum name to reduce ambiguous calls with system.threading.tasks
**Ready**
- [ x] Non-breaking change (fix or new feature that would not break existing functionality).
> change task status name

- src/Messaging/Common/Storage.cs
- src/Messaging/Events/TaskDispatchEvent.cs
- src/Messaging/Test/TaskCallbackEventTest.cs
- src/Messaging/Test/TaskDispatchEventTest.cs
Intermediate storage is always provided in the `TaskDispatchEvent` for the task plugins for storing intermediate data.
**Ready**
> Intermediate Storage for TaskDispatchEvent

- src/Messaging/Common/MessageConversionException.cs
- src/Messaging/Messages/Message.cs
- src/Messaging/Test/JsonMessageTest.cs
Throws `MessageConversionException` on failure to convert any event messages.
**Ready**
> Throws on error converting events

- src/Messaging/Events/TaskCallbackEvent.cs
- src/Messaging/Tests/TaskCallbackEventTest.cs
Move changes from release/0.1.6 to release/0.1.5
> Remove length limit for Idenity in TaskCallbackEvent

- src/Messaging/Events/TaskCallbackEvent.cs
- src/Messaging/Tests/TaskCallbackEventTest.cs
Removes the max length limit on the `Identity` property to allow other applications, such as Docker, to store an ID with value longer than 63 characters.
**Ready**
> Remove length limit for Identity

- doc/dependency_decisions.yml
- src/Messaging/Monai.Deploy.Messaging.csproj
- src/Messaging/Tests/Monai.Deploy.Messaging.Tests.csproj
- src/Plugins/RabbitMQ/RabbitMQHealthCheck.cs
- src/Plugins/RabbitMQ/Tests/Monai.Deploy.Messaging.RabbitMQ.Tests.csproj
- src/Plugins/RabbitMQ/Tests/RabbitMQHealthCheckTest.cs
- third-party-licenses.md
After running for a while, the health check API may exhaust all available channels in a RabbitMQ connection.
Fix to close the channel at the end of the check.
**Ready**
> Close channel at the end of health check

- .github/workflows/ci.yml
- src/Plugins/RabbitMQ/RabbitMqConnectionFactory.cs
> Ensures the connection is created before accessing

- src/Messaging/Events/ExportCompleteEvent.cs
- src/Messaging/Events/ExportStatus.cs
Update the `ExportCompleteEvent` to include a `FileExportStatus` for each file.
**Ready**
> Update export complete vent to include statuses of each file

- src/Plugins/RabbitMQ/Factory/RabbitMqConnectionFactory.cs
- src/Plugins/RabbitMQ/Logger.cs
Issues with connection being refreshed too much...
too resolve this I have put a check in on shutdown/exception events to check if the connection is still open.
**Ready**
> Connection resiliency take2

- src/Plugins/RabbitMQ/Factory/RabbitMqConnectionFactory.cs
- src/Plugins/RabbitMQ/RabbitMQHealthCheck.cs
Signed-off-by: Neil South <neil.south@answerdigital.com>
Fix to stop Rabbit channel being destroyed on every health check,
added `AutomaticRecoveryEnabled = true` flag 
**Ready**
> fix rabbitmq healthcheck

- src/Plugins/RabbitMQ/Tests/RabbitMQHealthCheckTest.cs
Fix to stop Rabbit channel being destroyed on every health check,  
added AutomaticRecoveryEnabled = true flag
**Ready**
> Adding fixed up test

- src/Messaging/API/ConnectionErrorArgs.cs
- src/Messaging/Events/ExportCompleteEvent.cs
- src/Messaging/Monai.Deploy.Messaging.csproj
- src/Plugins/RabbitMQ/Monai.Deploy.Messaging.RabbitMQ.csproj
- src/Plugins/RabbitMQ/Publisher/RabbitMqMessagePublisherService.cs
- src/Plugins/RabbitMQ/Subscriber/RabbitMqMessageSubscriberService.cs
Removes RMQ dependency from the base API library
**Ready**
> Remove RMQ dependency from the base API library

- src/Messaging/Events/TaskExecutionStatus.cs
Signed-off-by: Sam Rooke <sam.rooke@answerdigital.com>
Fixes # .
Added a new status, `PartialFail`, to the TaskExecutionStatus file for clinical review tasks.
**Ready**
> add PartialFail status to the task execution status

- doc/dependency_decisions.yml
- src/Messaging/Monai.Deploy.Messaging.csproj
- src/Messaging/Tests/Monai.Deploy.Messaging.Tests.csproj
- src/Plugins/RabbitMQ/Tests/Monai.Deploy.Messaging.RabbitMQ.Tests.csproj
- third-party-licenses.md
Signed-off-by: Sam Rooke <sam.rooke@answerdigital.com>
Fixes # .
Downgrading the `System.IO.Abstractions` package to prevent conflicting versions specified in MWM
**Ready**
> downgrade system.io.abstractions back to 17.2.3

- src/Plugins/RabbitMQ/Logger.cs
- src/Plugins/RabbitMQ/Subscriber/RabbitMqMessageSubscriberService.cs
- src/Plugins/RabbitMQ/Tests/Unit/RabbitMqMessageSubscriberServiceTest.cs
Added exception handling for previously created dead-letter queue, which prevents app startup if a RabbitMQ node is down temporarily.
**Ready**
> Added exception handling for unavailable previously created dead-letter queues

- src/Messaging/Events/ExportCompleteEvent.cs
Added field to export complete message, so we know if its a standard export or an external app request
**Ready**
> added export request to export complete message event

- doc/dependency_decisions.yml
- src/Messaging/Events/ExportCompleteEvent.cs
- src/Messaging/Monai.Deploy.Messaging.csproj
- src/Messaging/Tests/Monai.Deploy.Messaging.Tests.csproj
- src/Plugins/RabbitMQ/Factory/RabbitMqConnectionFactory.cs
- src/Plugins/RabbitMQ/Monai.Deploy.Messaging.RabbitMQ.csproj
- src/Plugins/RabbitMQ/Publisher/RabbitMqMessagePublisherService.cs
- src/Plugins/RabbitMQ/Subscriber/RabbitMqMessageSubscriberService.cs
- src/Plugins/RabbitMQ/Tests/Monai.Deploy.Messaging.RabbitMQ.Tests.csproj
- third-party-licenses.md
Remove unused references and clean up licenses
**Ready**
> Remove unused references and clean up licenses

- src/Messaging/Events/WorkflowRequestEvent.cs
- src/Messaging/Tests/WorkflowRequestMessageTest.cs
Fixes https://github.com/Project-MONAI/monai-deploy/issues/127
New data trigger and data origins to support multiple data sources/modalities
**Ready*
> Workflow Request Event to support multiple sources/modalities

- .github/workflows/ci.yml
- doc/dependency_decisions.yml
- global.json
- src/Messaging/Common/LoggingDataDictionary.cs
- src/Messaging/Common/MessageConversionException.cs
- src/Messaging/Common/MessageValidationException.cs
- src/Messaging/Common/ServiceException.cs
- src/Messaging/Configuration/ConfigurationException.cs
- src/Messaging/Monai.Deploy.Messaging.csproj
- src/Messaging/Tests/Common/ArtifactTypesTests.cs
- src/Messaging/Tests/Monai.Deploy.Messaging.Tests.csproj
- src/Plugins/RabbitMQ/Monai.Deploy.Messaging.RabbitMQ.csproj
- src/Plugins/RabbitMQ/Tests/Integration/HealthCheckTest.cs
- src/Plugins/RabbitMQ/Tests/Monai.Deploy.Messaging.RabbitMQ.Tests.csproj
- src/Plugins/RabbitMQ/Tests/Unit/RabbitMQHealthCheckTest.cs
- src/Plugins/RabbitMQ/Tests/Unit/RabbitMqMessagePublisherServiceTest.cs
- src/Plugins/RabbitMQ/Tests/Unit/RabbitMqMessageSubscriberServiceTest.cs
- third-party-licenses.md
> Update project to .NET 8
