Project-MONAI/monai-deploy-messaging

- .github/workflows/ci.yml
- CONTRIBUTING.md
- README.md
- src/Messaging/Messages/ExportRequestMessage.cs
- src/Messaging/Messages/JsonMessage.cs
- src/Messaging/Messages/Message.cs
- src/Messaging/Messages/MessageBase.cs
- src/Messaging/Monai.Deploy.Messaging.csproj
Changed from .net6 to .netstandard2.1
**Ready**
> Target .NET Standard 2.1

- src/Messaging/API/IMessageBrokerSubscriberService.cs
- src/Messaging/RabbitMq/RabbitMqMessageSubscriberService.cs
Fixes # .
Adds a no re-queue option to reject the subscription
**Ready**
- [ x] Non-breaking change (fix or new feature that would not break existing functionality).
> Add subscription no requeue reject

- src/Messaging/Common/Credentials.cs
Fixes # .
Add property to the taskdispatch model
**Ready**
> update task dispatch event

- src/Messaging/Events/TaskUpdateEvent.cs
Adds output artifacts to the taskUpdateEvent needed for ticket https://github.com/Project-MONAI/monai-deploy-workflow-manager/issues/52
**Ready**
> Add output artifacts to taskUpdateEvent

- src/Messaging/Events/TaskDispatchEvent.cs
- src/Messaging/Test/TaskDispatchEventTest.cs
Signed-off-by: Jack Schofield <jack.schofield@answerdigital.com>
Fixes # .
> add payload id to task dispatch

- src/Messaging/Events/TaskExecutionStatus.cs
Adds export status to task status enum
**Ready**
> add export status

- src/Messaging/Configuration/ConfigurationKeys.cs
- src/Messaging/RabbitMq/RabbitMqConnectionFactory.cs
- src/Messaging/RabbitMq/RabbitMqMessagePublisherService.cs
- src/Messaging/RabbitMq/RabbitMqMessageSubscriberService.cs
- src/Messaging/Test/RabbitMq/RabbitMqMessagePublisherServiceTest.cs
- src/Messaging/Test/RabbitMq/RabbitMqMessageSubscriberServiceTest.cs
> Options to enable secure RabbitMQ

- .github/workflows/ci.yml
We accidentally released 0.1.0 & 0.1.1 to NuGet when setting up CI in the begging, we have to bump up the version to 0.1.2.
**Ready**
> Release 0.1.2

- src/Messaging/Messages/JsonMessage.cs
- src/Messaging/Messages/Message.cs
- src/Messaging/Messages/MessageBase.cs
Fixes # .
Adds a requeue count to a message
**Ready**
> Add requeue count

- src/Messaging/Events/TaskCancellationEvent.cs
- src/Messaging/Messages/JsonMessage.cs
- src/Messaging/Messages/Message.cs
- src/Messaging/Tests/TaskCancellationEventTests.cs
implements #191 .
this is changes required for the background service in workflow manager for timeouts
**Ready**
> 191 background timeout service

- README.md
Signed-off-by: Lillie Dae <lillie.dae@answerdigital.com>
> trying to make build work

- src/Messaging/Events/TaskDispatchEvent.cs
- src/Messaging/Events/TaskExecutionStatus.cs
- src/Messaging/Events/TaskUpdateEvent.cs
Signed-off-by: Jack Schofield <jack.schofield@answerdigital.com>
Fixes # .
Removed the unnecessary statuses.
**Ready**
> update task execution

- doc/dependency_decisions.yml
- src/Messaging/Monai.Deploy.Messaging.csproj
- src/Messaging/Tests/Monai.Deploy.Messaging.Tests.csproj
- src/Plugins/RabbitMQ/Monai.Deploy.Messaging.RabbitMQ.csproj
- src/Plugins/RabbitMQ/Tests/Monai.Deploy.Messaging.RabbitMQ.Tests.csproj
- src/Plugins/package.sh
- third-party-licenses.md
- Update TargetFramework to `net6.0`
- Update third-party licenses
- Include licenses in NuGet & zip packages
**Ready**
> Use .NET 6 for all projects

- LICENSE
- README.md
Add license notice to landing page & LICENSE page.
**Ready*
> Update license notice

- src/Plugins/RabbitMQ/Logger.cs
- src/Plugins/RabbitMQ/Monai.Deploy.Messaging.RabbitMQ.csproj
- src/Plugins/RabbitMQ/RabbitMqMessageSubscriberService.cs
Signed-off-by: Neil South <neil.south@answerdigital.com>
adding logs for duration of message received to message Ack,ed
**Read**
> adding message timings

- src/Plugins/RabbitMQ/Factory/CreateChannelArguments.cs
- src/Plugins/RabbitMQ/Publisher/RabbitMqMessagePublisherService.cs
Signed-off-by: Lillie Dae <lillie.dae@answerdigital.com>
Fixes # .
**Ready**
> minor fix useSSL port not required

- src/Plugins/RabbitMQ/Subscriber/RabbitMqMessageSubscriberService.cs
- src/Plugins/RabbitMQ/Tests/RabbitMqMessageSubscriberServiceTest.cs
Signed-off-by: Neil South <neil.south@answerdigital.com>
Fixes # .
a unit test and logging of event duration, now based off message creation time.
**Ready**
> fix up unit test and eventDuration logging

- GitVersion.yml
- src/Plugins/RabbitMQ/Subscriber/RabbitMqMessageSubscriberService.cs
> Neildsouth patch 1

- src/Plugins/RabbitMQ/ChannelType.cs
- src/Plugins/RabbitMQ/Factory/IRabbitMQConnectionFactory.cs
- src/Plugins/RabbitMQ/Factory/RabbitMqConnectionFactory.cs
- src/Plugins/RabbitMQ/Publisher/RabbitMqMessagePublisherService.cs
- src/Plugins/RabbitMQ/RabbitMQHealthCheck.cs
- src/Plugins/RabbitMQ/Subscriber/RabbitMqMessageSubscriberService.cs
- src/Plugins/RabbitMQ/Tests/RabbitMQHealthCheckTest.cs
- src/Plugins/RabbitMQ/Tests/RabbitMqMessagePublisherServiceTest.cs
- src/Plugins/RabbitMQ/Tests/RabbitMqMessageSubscriberServiceTest.cs
Fixes # .
I Noticed that published ack's didnt seem to be working, it looks like best practice to have separate sub and pub channels, so Ive implemented that.
**Ready**
> Nds hunting rabbit

- GitVersion.yml
- doc/dependency_decisions.yml
- src/Messaging/Monai.Deploy.Messaging.csproj
- third-party-licenses.md
> Update release branch

- GitVersion.yml
- doc/dependency_decisions.yml
- src/Messaging/Common/LoggingDataDictionary.cs
- src/Messaging/Monai.Deploy.Messaging.csproj
- src/Messaging/Tests/Monai.Deploy.Messaging.Tests.csproj
- src/Plugins/RabbitMQ/ChannelType.cs
- src/Plugins/RabbitMQ/Factory/IRabbitMQConnectionFactory.cs
- src/Plugins/RabbitMQ/Factory/RabbitMqConnectionFactory.cs
- src/Plugins/RabbitMQ/Publisher/RabbitMqMessagePublisherService.cs
- src/Plugins/RabbitMQ/RabbitMQHealthCheck.cs
- src/Plugins/RabbitMQ/Subscriber/RabbitMqMessageSubscriberService.cs
- src/Plugins/RabbitMQ/Tests/Monai.Deploy.Messaging.RabbitMQ.Tests.csproj
- src/Plugins/RabbitMQ/Tests/RabbitMQHealthCheckTest.cs
- src/Plugins/RabbitMQ/Tests/RabbitMqMessagePublisherServiceTest.cs
- src/Plugins/RabbitMQ/Tests/RabbitMqMessageSubscriberServiceTest.cs
- third-party-licenses.md
Attempt to fix build number issues
> Attempt to fix build number issues

- src/Messaging/Events/FailureReason.cs
Signed-off-by: Jack Schofield <jack.schofield@answerdigital.com>
Fixes # .
> add rejected

- GitVersion.yml
- doc/dependency_decisions.yml
- src/Messaging/Monai.Deploy.Messaging.csproj
- src/Plugins/RabbitMQ/Tests/Monai.Deploy.Messaging.RabbitMQ.Tests.csproj
- third-party-licenses.md
Merged main back up into develop as it had become out-of-sync
**Ready**
> Merge main into develop

- src/Plugins/RabbitMQ/Logger.cs
- src/Plugins/RabbitMQ/Publisher/RabbitMqMessagePublisherService.cs
> Nds fix rabbit test

- src/Plugins/RabbitMQ/Subscriber/RabbitMqMessageSubscriberService.cs
Fixes # .
improve resiliency by extending try-catch area 
**Ready**
> ac-1619-extended-trycatch

- doc/dependency_decisions.yml
- src/Plugins/RabbitMQ/Subscriber/RabbitMqMessageSubscriberService.cs
- src/Plugins/RabbitMQ/Tests/Unit/RabbitMqMessageSubscriberServiceTest.cs
Fixes # .
fix up the code
**Ready**
> Ac 1619 nds

- src/Messaging/Events/EmailRequestEvent.cs
- src/Messaging/Tests/EmailRequestEventTest.cs
Adds EmailRequestEvent message
**Ready**
> added EmailRequestEvent message

- src/Messaging/Common/ExportRequestType.cs
- src/Messaging/Events/ExportRequestEvent.cs
- src/Messaging/Events/WorkflowRequestEvent.cs
adding new fields to messages for external app executions
**Ready**
> adding new fields to messages for external app executions

- src/Messaging/Common/ExportRequestType.cs
- src/Messaging/Events/WorkflowRequestEvent.cs
- src/Messaging/Tests/IServiceCollectionExtensionsTests.cs
- src/Messaging/Tests/TaskCallbackEventTest.cs
- src/Messaging/Tests/WorkflowRequestMessageTest.cs
- src/Plugins/RabbitMQ/Logger.cs
- src/Plugins/RabbitMQ/Publisher/RabbitMqMessagePublisherService.cs
- src/Plugins/RabbitMQ/Subscriber/RabbitMqMessageSubscriberService.cs
- src/Plugins/RabbitMQ/Tests/Integration/ReliabilityTest.cs
- src/Plugins/RabbitMQ/Tests/Unit/RabbitMqMessageSubscriberServiceTest.cs
Prepend event logging variables with `@` to avoid conflicts 
**Ready**
> Update logging variable name to avoid conflicts

- src/Messaging/Common/ArtifactType.cs
- src/Messaging/Common/ArtifactTypes.cs
Fixes # .
added folder artifact type
**Ready**
> added folder artifact type

- src/Messaging/Common/ArtifactTypes.cs
Fixes # .
Make list of modalities public
**Ready**
> Make list of modalities public

- src/Messaging/Events/ExportRequestEvent.cs
Adding payloadId so external apps can store data in same payload folder
> adding payloadId to export event

- src/Messaging/Events/ExportRequestEvent.cs
Fixes # .
making payloadId nullable
> making payloadId nullable

- src/Messaging/Events/ExportRequestEvent.cs
Fixes # .
adding comment
**Ready**
> adding comment

- src/Messaging/Events/ExportRequestEvent.cs
Fixes # .
unifying names
**Ready**
> unify naming

- src/Messaging/Common/ArtifactType.cs
adding HL7 as an artifact type
**Ready**
> adding HL7 type

- .github/workflows/ci.yml
- src/Messaging/Common/ArtifactTypes.cs
- src/Messaging/Tests/Common/ArtifactTypesTests.cs
added missing HL7 validation object
**Ready**
> adding missed validation and new test so it dont happen again

- .github/workflows/ci.yml
- doc/dependency_decisions.yml
- global.json
- src/Messaging/API/IMessageBrokerSubscriberService.cs
- src/Messaging/Common/LoggingDataDictionary.cs
- src/Messaging/Common/MessageConversionException.cs
- src/Messaging/Common/MessageValidationException.cs
- src/Messaging/Common/ServiceException.cs
- src/Messaging/Configuration/ConfigurationException.cs
- src/Messaging/Monai.Deploy.Messaging.csproj
- src/Messaging/Tests/Common/ArtifactTypesTests.cs
- src/Messaging/Tests/Monai.Deploy.Messaging.Tests.csproj
- src/Plugins/RabbitMQ/Monai.Deploy.Messaging.RabbitMQ.csproj
- src/Plugins/RabbitMQ/Tests/Integration/HealthCheckTest.cs
- src/Plugins/RabbitMQ/Tests/Monai.Deploy.Messaging.RabbitMQ.Tests.csproj
- src/Plugins/RabbitMQ/Tests/Unit/RabbitMQHealthCheckTest.cs
- src/Plugins/RabbitMQ/Tests/Unit/RabbitMqMessagePublisherServiceTest.cs
- src/Plugins/RabbitMQ/Tests/Unit/RabbitMqMessageSubscriberServiceTest.cs
- third-party-licenses.md
> Release 2.0.0

- .github/workflows/ci.yml
- doc/dependency_decisions.yml
- src/Plugins/RabbitMQ/ConfigurationKeys.cs
- src/Plugins/RabbitMQ/Subscriber/RabbitMqMessageSubscriberService.cs
- src/Plugins/RabbitMQ/Tests/Integration/ReliabilityTest.cs
Fixes # 271 (partially)
Partial fix as allowing setting of the prefetchCount via a config item allows you to set it to a higher value and therefore work around the issue.
**Ready**
> allowing prefectCount to be configurable

- .gitignore
> +semver: minor

- .gitignore
> Update .gitignore to do new release

- .github/workflows/ci.yml
> change upload action

- .gitignore
- GitVersion.yml
> +semver: patch version 2.0.1

- GitVersion.yml
> change next version
